// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goyrkevbtxchqobvwogq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdveXJrZXZidHhjaHFvYnZ3b2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzExMTUsImV4cCI6MjA2NTUwNzExNX0.n48NNGW_FkFCA9NmWviN3WpzsgLG4HUIx_NlrYzXahw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);